import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, GUID, UUIDMixin


class AnalyticsEvent(Base, UUIDMixin):
    """Raw events table for the feedback loop / learning system."""

    __tablename__ = "analytics_events"

    event_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    entity_type: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(GUID(), nullable=True, index=True)
    value: Mapped[float | None] = mapped_column(Float, nullable=True)
    event_metadata: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON string
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=datetime.utcnow,
        index=True,
    )

    def __repr__(self) -> str:
        return f"<AnalyticsEvent type={self.event_type} entity={self.entity_type}:{self.entity_id}>"


class ScoringWeightVersion(Base, UUIDMixin):
    """Tracks scoring weight recalibrations over time."""

    __tablename__ = "scoring_weight_versions"

    version: Mapped[int] = mapped_column(nullable=False, index=True)
    weights: Mapped[str] = mapped_column(Text, nullable=False)  # JSON string
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=datetime.utcnow,
    )

    def __repr__(self) -> str:
        return f"<ScoringWeightVersion v={self.version} active={self.is_active}>"


class DailyBriefing(Base, UUIDMixin):
    """Stored daily briefings generated by the Decision Engine."""

    __tablename__ = "daily_briefings"

    date: Mapped[str] = mapped_column(String(20), nullable=False, index=True)  # YYYY-MM-DD
    content: Mapped[str] = mapped_column(Text, nullable=False)  # JSON string
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=datetime.utcnow,
    )
    posted_to_slack: Mapped[bool] = mapped_column(default=False, nullable=False)

    def __repr__(self) -> str:
        return f"<DailyBriefing date={self.date}>"
